### ISSUE TITLE
Request to add Outbreak recruit icon

### ISSUE THREAD

**Issue by pawelmalak** [marcopixel/r6-operatoricons#19]
[Icon reference](https://cdnb.artstation.com/p/assets/images/images/009/666/329/large/jarvis-xciv-16x9-recruitob01.jpg)

It would be nice to have this icon in all 5 default recruit colors.

**Comment by marcopixel** [comment]
Oh right, those exist too ^^'

Gonna look at them in the next few days or someone from the others wanna have a try on them :)

**Comment by marcopixel** [comment]
High-res original reference:

**Comment by marcopixel** [comment]
Added with https://github.com/marcopixel/r6-operatoricons/commit/0790b76afe7307e995f8f5a179ab9fb548a044a6, thanks to @dtSniper for his help on the main shapes on this icon.
